version: '3.4'

services:
  financeservice.api:
    image: ${DOCKER_REGISTRY-}financeserviceapi
    build:
      context: .
      dockerfile: FinanceService.API/Dockerfile
    depends_on:
      - db

  db:
     image: "mcr.microsoft.com/mssql/server:2022-latest"
     ports:
       - "1433:1433"
     environment:
       SA_PASSWORD: "S3cur3P@ssW0rd!"
       ACCEPT_EULA: "Y"

volumes:
  finance-mysql-data: