version: '3.7'
services:
  db:
   image: mysql
   volumes:
     - finance-mysql-data:/var/lib/mysql
   environment:
     MYSQL_DATABASE: ${MYSQL_DATABASE:?database name not set}
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?database root password not set}  

  adminer:
   image: adminer
   restart: always
   ports:
     - 8080:8080

  finance-api:
    image: ${DOCKER_REGISTRY-}finance.api
    build:
      context: .
      dockerfile: src/FinanceService.Api/Dockerfile
    ports:
     - 5000:80
    depends_on:
     - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD:?database root password not set}
      MYSQL_DB: ${MYSQL_DATABASE:?database name not set}

volumes:
   finance-mysql-data: