## docker-compose.yml (Base)
# contains static configuration settings

version: '3.7'

## containers
services:


  # database server 
  # each service should have a seperate database on the server
  db:
    container_name: mysql_server
    image: mysql
  
  # database management 
  adminer:
   container_name: adminer
   image: adminer
   
  # identity api for authorization and user management
  identity-api:
    image: ${DOCKER_REGISTRY-}identity.api
    build:
        context: .
        dockerfile: Services/Identity/Dockerfile
    depends_on:
        - db
        
  # finance api 
  finance-api:
    image: ${DOCKER_REGISTRY-}finance.api
    build:
        context: .
        dockerfile: Services/Finance/src/FinanceService.Api/Dockerfile
    depends_on:
        - db
        - identity-api 
        
  # student api for registrar services
  student-api:
    image: ${DOCKER_REGISTRY-}studentserviceapi
    build:
      context: .
      dockerfile: Services/Student/src/StudentService.Api/Dockerfile
  
  # library api 
  library-api:
    image: ${DOCKER_REGISTRY-}library.api
    build:
        context: .
        dockerfile: Services/Library/src/LibraryService.Api/Dockerfile
    depends_on:
        - db
        - identity-api 
        - finance-api
  
  # student port for registrar services
  student-portal:
    image: ${DOCKER_REGISTRY-}student.portal
    build:
      context: .
      dockerfile: StudentPortal/Dockerfile

  # create gateways
  # all gateways use the same base image 
  student-gateway:  
    container_name: student_ocelot
    image: ${DOCKER_REGISTRY-}student.gateway
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile
  
  finance-gateway:
    container_name: finance_ocelot
    image: ${DOCKER_REGISTRY-}finance.gateway
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile

  library-gateway:
    container_name: library_ocelot
    image: ${DOCKER_REGISTRY-}library.gateway
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile
  
