# docker-compose.prod.yml (Base)
# production file with external/real dbs names for services
# Local dev-machine firewall range must be opened at 5100-5100
# CLI command for docker-compose.prod file:
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up
version: '3.7'


services:
  mysql-server:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
       - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
          MYSQL_ROOT_PASSWORD: tiaspbiqe2r
    ports:
      - "5433:1433"
  
  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5100:80" # Only service to keep external port

  student-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://${SESC_PROD_EXTERNAL_DNS_NAME_OR_IP}:5100
    ports:
      - "80" # The API Gateway redirects and access through the internal port (80).

  library-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://${SESC_PROD_EXTERNAL_DNS_NAME_OR_IP}:5100
    ports:
      - "80"
 
  finance-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://${SESC_PROD_EXTERNAL_DNS_NAME_OR_IP}:5100
    ports:
      - "80"

  student-portal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"


  # add ocelot configuration files for each gateway  
  student-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity-api
    ports:
      - "80"
    volumes:
      - ./ApiGateways/Web.Bff.StudentPortal/apigw:/app/ocelot
  
  finance-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity-api
    ports:
      - "80"
    volumes:
      - ApiGateways/Web.Bff.FinancePortal/apigw:/app/ocelot

  library-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity-api
    ports:
      - "80"
    volumes:
      - ApiGateways/Web.Bff.LibraryPortal/apigw:/app/ocelot