## docker-compose.yml (Base)
# contains static configuration settings

version: '3.7'

## containers
services:
  # database server 
  # each service should have a seperate database on the server
  db:
    container_name: Database.Server
    image: mysql
  
  # database management 
  db-management:
   container_name: Database.Management
   image: adminer
   depends_on:
        - db
   
  # identity api for authorization and user management
  identity-api:
    image: ${DOCKER_REGISTRY-}identity.api
    hostname: identity-api
    build:
        context: .
        dockerfile: Services/Identity/Dockerfile
    depends_on:
        - db
        
  # finance api 
  finance-api:
    image: ${DOCKER_REGISTRY-}finance.api
    hostname: finance-api
    build:
        context: .
        dockerfile: Services/Finance/src/FinanceService.Api/Dockerfile
    depends_on:
        - db
        
  # student api for registrar services
  student-api:
    image: ${DOCKER_REGISTRY-}studentservice.api
    hostname: student-api
    build:
      context: .
      dockerfile: Services/Student/src/StudentService.Api/Dockerfile
    depends_on:
        - db
  
  # library api 
  library-api:
    image: ${DOCKER_REGISTRY-}library.api
    hostname: library-api
    build:
        context: .
        dockerfile: Services/Library/src/LibraryService.Api/Dockerfile
    depends_on:
        - db
  
  # student port for registrar services
  student-portal:
    image: ${DOCKER_REGISTRY-}student.portal     
    hostname: student-portal
    build:
      context: .
      dockerfile: StudentPortal/Dockerfile
    depends_on:
      - student-gateway

  # student port for finance services
  finance-portal:
    image: ${DOCKER_REGISTRY-}finance.portal     
    hostname: finance-portal
    build:
      context: .
      dockerfile: FinancePortal/Dockerfile
    depends_on:
      - finance-gateway

  # create gateways
  # all gateways use the same base image 
  student-gateway:  
    container_name: StudentPortal.Gateway
    hostname: student-gateway
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile  
    links:
        - finance-api
        - student-api
        - library-api
        - identity-api

  
  finance-gateway:
    container_name: FinancePortal.Gateway
    hostname: finance-gateway
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile 
    links:
        - finance-api
        - identity-api 

  library-gateway:
    container_name: LibraryPortal.Gateway
    hostname: library-gateway
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile
    links:
        - finance-api
        - library-api
        - identity-api 
  
