## docker-compose.override.yml 
# extended configuration for development environment
version: '3.7'

services:

  # for development and testing all databases are in the same docker container to keep memory requirements low
  # for development and testing  all databases have the same root user and password
  mysql-server:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # script to create seperate databases 
    volumes:
       - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?database root password not set}
          
    # map host port to container port
    # same port for development and testing because all service databases in one container 
    ports:
      - "3306:3306"
  
  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    
    ports:
      - "5100:80"

  student-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://${EXTERNAL_DNS_NAME_OR_IP}:5100
    ports:
      - "5101:80"

  library-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://${EXTERNAL_DNS_NAME_OR_IP}:5100
    ports:
      - "5102:80"
 
  finance-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://${EXTERNAL_DNS_NAME_OR_IP}:5100
    ports:
      - "5103:80"

  student-portal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"

  # add ocelot configuration files for each gateway  
  # API Gateway redirects and access through the internal port (80)
  # External Ports(5200-5202) kept for debugging
  student-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://student-api
    ports:
    
      - "5200:80"
    volumes:
      - ./ApiGateways/Web.Bff.StudentPortal/ocelot:/app/configuration
  
  finance-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://finance-api
    ports:
      - "5201:80"
    volumes:
      - ./ApiGateways/Web.Bff.FinancePortal/ocelot:/app/configuration

  library-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://library-api
    ports:
      - "5202:80"
    volumes:
      - ./ApiGateways/Web.Bff.LibraryPortal/ocelot:/app/configuration